name: Release

on:
  push:
    branches-ignore:
      - '!main' # Ignore branches that are not main
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # Use custom token to trigger following workflows
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Update latest versions of native Android and iOS sdks
            More info: https://developers.didomi.io/cmp/mobile-sdk
          draft: false
          prerelease: false
