name: Update

# Triggered manually or on release creation
on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment (major, minor, patch)"
        required: true
        default: "patch"
      force:
        description: "Force update (even if sdk is up to date)"
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update version and dependencies
    runs-on: macos-latest # required for pod info / update

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if React Native SDK requires update
        if: github.event.inputs.force != 'true'
        run: |
          echo "Force: ${{ github.event.inputs.force }}"
          bash .github/scripts/check_before_update.sh

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: yarn install

      - name: Update React Native SDK
        run: |
          echo "Increment: ${{ github.event.inputs.increment }}"
          bash .github/scripts/update.sh ${{ github.event.inputs.increment }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: "cmp-mobile@didomi.io"
          author_name: "Auto-Bot"
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update Native SDKs and increment ${{ github.event.inputs.increment }} version"

  # tag:
  #   name: Tag
  #   needs: update
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set React Native version as ENV
  #       run: |
  #         echo "rn_version=$(sh .github/scripts/extract_version.sh)" >> $GITHUB_ENV

  #     - name: Print React Native Version
  #       run: |
  #         echo "React Native version is: ${{ env.rn_version }}"

  #     - name: Create tag
  #       uses: actions/github-script@v3
  #       with:
  #         github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # Use custom token to trigger following workflows
  #         script: |
  #           github.git.createRef({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             ref: "refs/tags/${{ env.rn_version }}",
  #             sha: context.sha
  #           })
